### PR TITLE
Fixed cmake files for windows.

### PR DESCRIPTION
**Pull request by Tereius**

### CODE REVIEW

**Comment by msrd0** [comment]
I don't own a windows machine myself ... but I don't think that these changes are sufficient. Have a look at [QtWebAppConfig.cmake.in](https://github.com/msrd0/QtWebApp/blob/master/QtWebApp/cmake/QtWebAppConfig.cmake.in#L29) - this will search for `libQtWebApp<module>.so`, but not .lib or .dll.

By the way why does windows require archive destination? I guess when compiling a shared lib there are no archives, but correct me if my way of thinking is limited to unix.

**Comment by Tereius** [comment]
On windows cmake fails because archive and runtime destinations are missing. The cmake docs state: "For DLL platforms the DLL part of a shared library is treated as a RUNTIME target and the corresponding import library is treated as an ARCHIVE target".

I have overlooked the file [QtWebAppConfig.cmake.in](https://github.com/msrd0/QtWebApp/blob/5873d6062cf74f4929299ce35db7d45193b6cf13/QtWebApp/cmake/QtWebAppConfig.cmake.in) that exports the library targets somehow. You are right: the target import using the generated file won't work on windows machines. But at a first glance this seems unnecessary complicated. Cmake provides a platform independent functionality with ```install(EXPORT ...)``` but in [CMakeLists.txt](https://github.com/msrd0/QtWebApp/blob/5873d6062cf74f4929299ce35db7d45193b6cf13/QtWebApp/httpserver/CMakeLists.txt#L39-L40) it’s commented out. Is there a reason for not using ```install(EXPORT ...)```?

**Comment by msrd0** [comment]
[This commit](https://github.com/msrd0/QtWebApp/commit/f81bd82421c1671bbf95eb1c16dcc4f7b549ab1e) should now fix those issues and use standard cmake exports.

Can you test this on windows and tell me whether it works?

**Comment by Tereius** [comment]
Yes it works. Thank you.

**Pull request merged**
