### PR TITLE
Fix compilation with clang: %i does not work for quint64

### PR DESCRIPTION
**Pull request by gladhorn**
This allows compiling QtWebApp with clang.

### CODE REVIEW

**Comment by msrd0** [comment]
I can unfortunately not reproduce this, neither locally on ArchLinux, nor on GitHub actions. What is your setup?

**Comment by gladhorn** [comment]
Good question, I had this floating around for a while... let me try on macOS.

**Comment by gladhorn** [comment]
I get this warning:
```
qtwebapp/QtWebApp/httpserver/staticfilecontroller.cpp:37: error: format specifies type 'int' but the argument has type 'qsizetype' (aka 'long long') [-Werror,-Wformat]
../thirdparty/device/qtwebapp/QtWebApp/httpserver/staticfilecontroller.cpp:37:72: error: format specifies type 'int' but the argument has type 'qsizetype' (aka 'long long') [-Werror,-Wformat]
        qDebug("StaticFileController: cache timeout=%i, size=%i",cacheTimeout,cache.maxCost());
                                                             ~~               ^~~~~~~~~~~~~~~
                                                             %lli
```

**Comment by msrd0** [comment]
Hm, given that we use `-Werror=format` on all platforms except MSVC, this should fail always or never, not just on your local machine. Do you have any idea how to reproduce this in the CI?

 Also, it looks like the error message you've posted above is a different location that what you fixed in this PR.

**Comment by gladhorn** [comment]
You're right. Seems like I get a bunch of those when building an app that links qtwebapp. I can close this for now...

**Pull request closed without merging**
