### PR TITLE
Add a minimal Windows CI

### PR DESCRIPTION
**Pull request by gladhorn**
Just try to build qtwebapp at all with mingw.

### CODE REVIEW

**Comment by gladhorn** [comment]
I never really understood why QtWebApp has no top level cmakelists.txt. Better luck next time :) maybe this actually has a chance to work. Debugging github actions is such a pain... probably this will take 20 attempts...

**Comment by gladhorn** [comment]
I didn't see how to easily merge it into the existing file, maybe it's OK to have the windows CI separate?
Otherwise one needs a lot of if statements in githubs yaml syntax and that is not really fun to write in my experience.
Now it builds qtwebapp without caring about the examples. Maybe this can go in as basis and we iterate on top of it?

**Comment by msrd0** [comment]
> I didn't see how to easily merge it into the existing file

Just add a second `build-windows` key below the `build` key in the existing file

**Comment by msrd0** [comment]
> Maybe this can go in as basis and we iterate on top of it?

Sounds good

**Comment by msrd0** [comment]
Superseeded by #23

**Pull request closed without merging**
